version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db_help_bot
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracking_help_bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_URL: ${DB_URL}

    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8080:8080"

volumes:
  postgres_data: